-- Seed hadiths for Jami at-Tirmidhi Book 1 (Purification) - Hadiths 1-50
-- These link to the chapters table via collection_hadiths

-- First insert the hadiths into the hadiths table
INSERT INTO hadiths (collection, book_number, hadith_number, narrator, arabic_text, english_translation, grade, reference) VALUES
('Jami at-Tirmidhi', 1, 1, 'Ibn Umar', 'لاَ تُقْبَلُ صَلاَةٌ بِغَيْرِ طُهُورٍ وَلاَ صَدَقَةٌ مِنْ غُلُولٍ', 'The Prophet said: Salat will not be accepted without purification, nor Charity from Ghulul.', 'sahih', 'Jami at-Tirmidhi 1'),
('Jami at-Tirmidhi', 1, 2, 'Abu Hurairah', 'إِذَا تَوَضَّأَ الْعَبْدُ الْمُسْلِمُ فَغَسَلَ وَجْهَهُ خَرَجَتْ مِنْ وَجْهِهِ كُلُّ خَطِيئَةٍ', 'When a Muslim performs Wudu, washing his face, every evil he looked at with his eyes leaves with the water, until he becomes free of sin.', 'sahih', 'Jami at-Tirmidhi 2'),
('Jami at-Tirmidhi', 1, 3, 'Ali ibn Abi Talib', 'مِفْتَاحُ الصَّلاَةِ الطُّهُورُ وَتَحْرِيمُهَا التَّكْبِيرُ وَتَحْلِيلُهَا التَّسْلِيمُ', 'The key to Salat is purification, its Tahrim is the Takbir, and its Tahlil is the Taslim.', 'hasan', 'Jami at-Tirmidhi 3'),
('Jami at-Tirmidhi', 1, 4, 'Jabir bin Abdullah', 'مِفْتَاحُ الْجَنَّةِ الصَّلاَةُ وَمِفْتَاحُ الصَّلاَةِ الْوُضُوءُ', 'The key to Paradise is Salat, and the key to Salat is Wudu.', 'hasan', 'Jami at-Tirmidhi 4'),
('Jami at-Tirmidhi', 1, 5, 'Anas bin Malik', 'كَانَ النَّبِيُّ إِذَا دَخَلَ الْخَلاَءَ قَالَ اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْخُبْثِ وَالْخَبَائِثِ', 'When the Prophet entered the toilet he would say: O Allah Indeed I seek refuge in You from Al-Khubthi and Al-Khabaith.', 'sahih', 'Jami at-Tirmidhi 5'),
('Jami at-Tirmidhi', 1, 6, 'Anas bin Malik', 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْخُبْثِ وَالْخَبَائِثِ', 'When the Prophet would enter the toilet he said: O Allah! Indeed I seek refuge in You from Al-Khubith and Al-Khabaith.', 'sahih', 'Jami at-Tirmidhi 6'),
('Jami at-Tirmidhi', 1, 7, 'Aishah', 'كَانَ النَّبِيُّ إِذَا خَرَجَ مِنَ الْخَلاَءِ قَالَ غُفْرَانَكَ', 'When the Prophet would exit the toilet he would say: Ghufranak (Your Forgiveness).', 'sahih', 'Jami at-Tirmidhi 7'),
('Jami at-Tirmidhi', 1, 8, 'Abu Ayyub Al-Ansari', 'إِذَا أَتَيْتُمُ الْغَائِطَ فَلاَ تَسْتَقْبِلُوا الْقِبْلَةَ بِغَائِطٍ وَلاَ بَوْلٍ وَلَكِنْ شَرِّقُوا أَوْ غَرِّبُوا', 'When one of you arrives to defecate, then let none of you face the Qiblah, but have it east or west of you.', 'sahih', 'Jami at-Tirmidhi 8'),
('Jami at-Tirmidhi', 1, 9, 'Jabir bin Abdullah', 'نَهَى النَّبِيُّ أَنْ نَسْتَقْبِلَ الْقِبْلَةَ بِبَوْلٍ فَرَأَيْتُهُ قَبْلَ أَنْ يُقْبَضَ بِعَامٍ يَسْتَقْبِلُهَا', 'The Prophet prohibited us from facing the Qiblah while urinating. Then I saw him facing it a year before he died.', 'hasan', 'Jami at-Tirmidhi 9'),
('Jami at-Tirmidhi', 1, 10, 'Abu Qatadah', 'رَأَى النَّبِيَّ يَبُولُ مُسْتَقْبِلَ الْقِبْلَةِ', 'Abu Qatadah narrated that he saw the Prophet urinating while facing the Qiblah.', 'hasan', 'Jami at-Tirmidhi 10'),
('Jami at-Tirmidhi', 1, 11, 'Ibn Umar', 'رَقِيتُ يَوْمًا عَلَى بَيْتِ حَفْصَةَ فَرَأَيْتُ النَّبِيَّ عَلَى حَاجَتِهِ مُسْتَقْبِلَ الشَّأْمِ مُسْتَدْبِرَ الْكَعْبَةِ', 'Ibn Umar said: One day I climbed on Hafsah house, and I saw the Prophet relieving himself while facing Ash-Sham, with his back toward the Kabah.', 'sahih', 'Jami at-Tirmidhi 11'),
('Jami at-Tirmidhi', 1, 12, 'Aishah', 'مَنْ حَدَّثَكُمْ أَنَّ النَّبِيَّ كَانَ يَبُولُ قَائِمًا فَلاَ تُصَدِّقُوهُ مَا كَانَ يَبُولُ إِلاَّ قَاعِدًا', 'Aishah said: Whoever told you that the Prophet urinated while standing, do not believe him. He would not urinate except while sitting.', 'hasan', 'Jami at-Tirmidhi 12'),
('Jami at-Tirmidhi', 1, 13, 'Hudhaifah', 'أَتَى سُبَاطَةَ قَوْمٍ فَبَالَ عَلَيْهَا قَائِمًا فَأَتَيْتُهُ بِوَضُوءٍ فَتَوَضَّأَ وَمَسَحَ عَلَى خُفَّيْهِ', 'The Messenger came to a waste area, urinated while standing. I brought him water for Wudu. He performed Wudu and wiped over his Khuff.', 'sahih', 'Jami at-Tirmidhi 13'),
('Jami at-Tirmidhi', 1, 14, 'Anas', 'كَانَ النَّبِيُّ إِذَا أَرَادَ الْحَاجَةَ لَمْ يَرْفَعْ ثَوْبَهُ حَتَّى يَدْنُوَ مِنَ الأَرْضِ', 'When the Prophet wanted to relieve himself, he would not raise his garment until he was close to the ground.', 'daif', 'Jami at-Tirmidhi 14'),
('Jami at-Tirmidhi', 1, 15, 'Abu Qatadah', 'نَهَى النَّبِيُّ أَنْ يَمَسَّ الرَّجُلُ ذَكَرَهُ بِيَمِينِهِ', 'The Prophet prohibited that a man should touch his private part with his right hand.', 'sahih', 'Jami at-Tirmidhi 15'),
('Jami at-Tirmidhi', 1, 16, 'Salman Al-Farisi', 'نَهَانَا أَنْ نَسْتَقْبِلَ الْقِبْلَةَ بِغَائِطٍ أَوْ بَوْلٍ وَأَنْ نَسْتَنْجِيَ بِالْيَمِينِ أَوْ بِأَقَلَّ مِنْ ثَلاَثَةِ أَحْجَارٍ', 'He prohibited us from facing the Qiblah when defecating, performing Istinja with the right hand, using less than three stones, and using dung or bones for Istinja.', 'sahih', 'Jami at-Tirmidhi 16'),
('Jami at-Tirmidhi', 1, 17, 'Abdullah bin Masud', 'خَرَجَ النَّبِيُّ لِحَاجَتِهِ فَقَالَ الْتَمِسْ لِي ثَلاَثَةَ أَحْجَارٍ فَأَتَيْتُهُ بِحَجَرَيْنِ وَرَوْثَةٍ فَأَخَذَ الْحَجَرَيْنِ وَأَلْقَى الرَّوْثَةَ وَقَالَ إِنَّهَا رِكْسٌ', 'The Messenger went out to relieve himself and said: Bring me three stones. I came with two stones and dung. He took the stones, left the dung, and said: It is Riks (filthy).', 'sahih', 'Jami at-Tirmidhi 17'),
('Jami at-Tirmidhi', 1, 18, 'Abdullah bin Masud', 'لاَ تَسْتَنْجُوا بِالرَّوْثِ وَلاَ بِالْعِظَامِ فَإِنَّهُ زَادُ إِخْوَانِكُمْ مِنَ الْجِنِّ', 'Do not perform Istinja with dung nor with bones. For indeed it is provisions for your brothers among the Jinn.', 'sahih', 'Jami at-Tirmidhi 18'),
('Jami at-Tirmidhi', 1, 19, 'Aishah', 'مُرْنَ أَزْوَاجَكُنَّ أَنْ يَسْتَطِيبُوا بِالْمَاءِ فَإِنِّي أَسْتَحْيِيهِمْ فَإِنَّ رَسُولَ اللَّهِ كَانَ يَفْعَلُهُ', 'Encourage your husbands to clean themselves with water, for I am too shy of them, and the Messenger of Allah would do that.', 'sahih', 'Jami at-Tirmidhi 19');
