-- Seed sunnah practices days 148-365
-- Continuing from batch 1

-- Days 148-177: Prayer & Worship
INSERT INTO sunnah_practices (title, description, category_id, hadith_ref, day_of_year) VALUES
  ('Pray Salat al-Ishraq', 'Pray two rak''ah after sunrise. The Prophet (PBUH) encouraged this prayer for its immense reward.', 'salah', 'Muslim 720', 148),
  ('Perfect Your Sujud', 'Make your prostration unhurried. The Prophet (PBUH) would remain in sujud reciting lengthy supplications.', 'salah', 'Bukhari 821', 149),
  ('Pray Behind the Imam Attentively', 'When praying in congregation, follow the imam precisely without rushing ahead.', 'salah', 'Bukhari 722', 150),
  ('Make Dua Between Adhan and Iqamah', 'Supplication between the call to prayer and the start of prayer is not rejected.', 'daily', 'Abu Dawud 521', 151),
  ('Pray Salat al-Tawbah', 'When you commit a sin, perform two rak''ah of repentance and seek Allah''s forgiveness.', 'salah', 'Abu Dawud 1521', 152),
  ('Straighten the Prayer Rows', 'Help straighten the rows before congregational prayer.', 'salah', 'Muslim 436', 153),
  ('Recite Ayat al-Kursi After Salah', 'After every obligatory prayer, recite Ayat al-Kursi.', 'daily', 'An-Nasa''i', 154),
  ('Pray with Khushu', 'Focus on the meaning of what you recite and feel the presence of Allah during prayer.', 'salah', 'Bukhari 6265', 155),
  ('Make Istikharah for Decisions', 'Before important decisions, pray two rak''ah of Istikhara and make the prescribed dua.', 'salah', 'Bukhari 1166', 156),
  ('Pray Salat al-Hajah', 'When in need, perform two rak''ah and supplicate to Allah with sincerity.', 'salah', 'Tirmidhi 479', 157),
  ('Attend Jumu''ah Early', 'Go to Friday prayer early. Angels record those who come first.', 'salah', 'Bukhari 929', 158),
  ('Read Surah Al-Kahf on Friday', 'Whoever reads Surah Al-Kahf on Friday will have a light between two Fridays.', 'worship', 'Al-Hakim', 159),
  ('Make Abundant Salawat on Friday', 'Send blessings upon the Prophet (PBUH) abundantly on Friday.', 'daily', 'Abu Dawud 1047', 160),
  ('Pray Tahajjud', 'Wake in the last third of the night and pray voluntary prayers.', 'salah', 'Bukhari 1145', 161),
  ('Recite Morning Adhkar', 'Say the morning remembrances after Fajr prayer.', 'daily', 'Abu Dawud 5068', 162),
  ('Recite Evening Adhkar', 'Say the evening remembrances after Asr prayer.', 'daily', 'Abu Dawud 5069', 163),
  ('Pray Duha Prayer', 'Pray 2-8 rak''ah after sunrise until just before Dhuhr.', 'salah', 'Muslim 748', 164),
  ('Fast Mondays and Thursdays', 'The Prophet (PBUH) used to fast on Mondays and Thursdays.', 'worship', 'Tirmidhi 745', 165),
  ('Give Sadaqah Today', 'Give charity, even if small. Sadaqah extinguishes sins like water extinguishes fire.', 'worship', 'Tirmidhi 614', 166),
  ('Visit the Sick', 'Visiting the sick is a right of a Muslim upon another Muslim.', 'people', 'Muslim 2162', 167),
  ('Reconcile Between People', 'Making peace between people is better than voluntary prayer and fasting.', 'people', 'Abu Dawud 4919', 168),
  ('Lower Your Gaze', 'Guard your eyesight. The Prophet (PBUH) said the glance is one of the poisoned arrows of Shaytan.', 'character', 'Al-Hakim', 169),
  ('Be Patient in Adversity', 'Patience is a light. The Prophet (PBUH) said amazing is the affair of the believer.', 'character', 'Muslim 2999', 170),
  ('Remember Death Often', 'The Prophet (PBUH) said: Frequently remember the destroyer of pleasures — death.', 'worship', 'Tirmidhi 2307', 171),
  ('Perform Wudu Before Sleep', 'The Prophet (PBUH) would perform wudu before sleeping.', 'sleep', 'Bukhari 247', 172),
  ('Sleep on Your Right Side', 'The Prophet (PBUH) would sleep on his right side after making wudu.', 'sleep', 'Bukhari 247', 173),
  ('Recite Last Two Ayat of Al-Baqarah', 'Before sleeping, recite the last two verses of Surah Al-Baqarah.', 'sleep', 'Bukhari 5009', 174),
  ('Dust Your Bed Before Sleeping', 'The Prophet (PBUH) would dust his bed three times before lying down.', 'sleep', 'Bukhari 6320', 175),
  ('Say Bismillah When Locking Your Door', 'Say Bismillah when closing your door at night.', 'sleep', 'Bukhari 5623', 176),
  ('Wake Up and Praise Allah', 'Upon waking, say: Alhamdulillahil-ladhi ahyana ba''da ma amatana.', 'daily', 'Bukhari 6324', 177),

  -- Days 178-207: Character & Social
  ('Smile at Others', 'Your smile in the face of your brother is charity.', 'character', 'Tirmidhi 1956', 178),
  ('Speak Good or Keep Silent', 'Whoever believes in Allah and the Last Day, let him speak good or remain silent.', 'character', 'Bukhari 6018', 179),
  ('Remove Harm from the Path', 'Removing something harmful from the road is an act of charity.', 'character', 'Muslim 1914', 180),
  ('Be Gentle in All Affairs', 'Allah is gentle and loves gentleness in all affairs.', 'character', 'Muslim 2593', 181),
  ('Forgive Others', 'Be forgiving. Allah will honor you. Be humble. Allah will raise you.', 'character', 'Muslim 2588', 182),
  ('Keep Promises', 'The signs of a hypocrite are three: when he speaks he lies, when he promises he breaks it.', 'character', 'Bukhari 33', 183),
  ('Control Your Anger', 'The strong person is not the one who wrestles but who controls himself when angry.', 'character', 'Bukhari 6114', 184),
  ('Be Truthful', 'Truthfulness leads to righteousness, and righteousness leads to Paradise.', 'character', 'Bukhari 6094', 185),
  ('Avoid Backbiting', 'Backbiting is mentioning your brother with what he dislikes.', 'character', 'Muslim 2589', 186),
  ('Show Gratitude', 'He who does not thank people does not thank Allah.', 'people', 'Abu Dawud 4811', 187),
  ('Visit Your Neighbors', 'Jibril kept advising me about the neighbor until I thought he would inherit.', 'people', 'Bukhari 6014', 188),
  ('Feed Others', 'The best of you is the one who feeds others.', 'people', 'Ahmad', 189),
  ('Help the Needy', 'The one who looks after a widow or poor person is like a mujahid.', 'people', 'Bukhari 5353', 190),
  ('Honor Your Parents', 'Paradise lies at the feet of your mother.', 'people', 'An-Nasa''i 3104', 191),
  ('Maintain Family Ties', 'The one who severs family ties will not enter Paradise.', 'people', 'Bukhari 5984', 192),
  ('Return the Greeting of Salam', 'When greeted with a greeting, respond with better or at least equal.', 'people', 'Quran 4:86', 193),
  ('Initiate Salam', 'The best of the two is the one who initiates the greeting of peace.', 'people', 'Bukhari 6077', 194),
  ('Be Kind to Animals', 'A woman entered Hell because of a cat she imprisoned without feeding.', 'character', 'Bukhari 3318', 195),
  ('Show Mercy', 'The merciful are shown mercy by the Most Merciful.', 'character', 'Abu Dawud 4941', 196),
  ('Avoid Suspicion', 'Avoid suspicion, for suspicion is the worst of false tales.', 'character', 'Bukhari 6064', 197),
  ('Be Humble', 'No one who has an atom''s weight of arrogance will enter Paradise.', 'character', 'Muslim 91', 198),
  ('Seek Knowledge', 'Seeking knowledge is an obligation upon every Muslim.', 'worship', 'Ibn Majah 224', 199),
  ('Teach Others', 'The best of you are those who learn the Quran and teach it.', 'worship', 'Bukhari 5027', 200),
  ('Be Just', 'Be just; that is nearer to piety.', 'character', 'Quran 5:8', 201),
  ('Avoid Jealousy', 'Beware of jealousy, for it devours good deeds as fire devours wood.', 'character', 'Abu Dawud 4903', 202),
  ('Guard Your Tongue', 'Most of the sins of the children of Adam are from the tongue.', 'character', 'Tabarani', 203),
  ('Be Generous', 'The Prophet (PBUH) was the most generous of people.', 'character', 'Bukhari 6', 204),
  ('Make Dua for Others', 'The dua of a Muslim for his brother in his absence is answered.', 'daily', 'Muslim 2733', 205),
  ('Console the Grieving', 'Whoever consoles a bereaved person will have a garment of honor.', 'people', 'Tirmidhi 1073', 206),
  ('Spread Knowledge', 'Convey from me, even if it is one verse.', 'worship', 'Bukhari 3461', 207),

  -- Days 208-237: Eating, Health & Cleanliness
  ('Say Bismillah Before Eating', 'Mention the name of Allah before eating and eat with your right hand.', 'food', 'Bukhari 5376', 208),
  ('Eat with Right Hand', 'The Prophet (PBUH) said: Eat with your right hand.', 'food', 'Muslim 2020', 209),
  ('Eat from What Is Near You', 'O young boy, mention Allah, eat with your right hand, and eat from what is near you.', 'food', 'Bukhari 5376', 210),
  ('Don''t Criticize Food', 'The Prophet (PBUH) never criticized any food. If he liked it he ate it; if not he left it.', 'food', 'Bukhari 5409', 211),
  ('Eat in Moderation', 'Fill a third for food, a third for drink, and a third for air.', 'food', 'Tirmidhi 2380', 212),
  ('Drink Water in Three Sips', 'The Prophet (PBUH) used to drink water in three breaths.', 'food', 'Muslim 2028', 213),
  ('Don''t Blow on Food', 'The Prophet (PBUH) forbade blowing on food and drink.', 'food', 'Tirmidhi 1887', 214),
  ('Share Food with Neighbors', 'If you cook broth, increase the water and share with your neighbors.', 'food', 'Muslim 2625', 215),
  ('Eat Dates', 'Whoever eats seven Ajwa dates in the morning will not be harmed by poison or magic.', 'health', 'Bukhari 5445', 216),
  ('Drink Honey', 'Honey is a healing for mankind.', 'health', 'Quran 16:69', 217),
  ('Use Black Seed', 'In the black seed is a cure for every disease except death.', 'health', 'Bukhari 5688', 218),
  ('Use Olive Oil', 'Eat olive oil and anoint yourselves with it, for it is from a blessed tree.', 'health', 'Tirmidhi 1851', 219),
  ('Eat with Others', 'Gather together for your meals and mention Allah''s name, it will be blessed.', 'food', 'Abu Dawud 3764', 220),
  ('Say Alhamdulillah After Eating', 'Whoever eats and says Alhamdulillah, his past sins will be forgiven.', 'food', 'Tirmidhi 1816', 221),
  ('Lick Your Fingers After Eating', 'The Prophet (PBUH) would lick his fingers after eating.', 'food', 'Muslim 2032', 222),
  ('Use Siwaak', 'If it would not be too difficult for my ummah, I would have ordered them to use siwaak.', 'home', 'Bukhari 887', 223),
  ('Trim Your Nails', 'The Prophet (PBUH) set a time limit of forty days for trimming nails.', 'home', 'Muslim 258', 224),
  ('Keep Hair Tidy', 'Whoever has hair, let him honor it.', 'home', 'Abu Dawud 4163', 225),
  ('Apply Perfume', 'The Prophet (PBUH) loved perfume and would not refuse it.', 'home', 'Bukhari 2582', 226),
  ('Wash Hands Before Eating', 'The Prophet (PBUH) would wash his hands before and after meals.', 'home', 'Tirmidhi 1846', 227),
  ('Take a Bath on Friday', 'Taking a bath on Friday is obligatory for every adult Muslim.', 'home', 'Bukhari 879', 228),
  ('Wear Clean Clothes', 'Allah is beautiful and loves beauty.', 'home', 'Muslim 91', 229),
  ('Enter Bathroom with Left Foot', 'Say Bismillah and enter with the left foot.', 'home', 'Tirmidhi 606', 230),
  ('Exit Bathroom with Right Foot', 'Say Ghufranaka when exiting the bathroom.', 'home', 'Abu Dawud 30', 231),
  ('Cover Your Mouth When Yawning', 'When one of you yawns, let him cover his mouth.', 'health', 'Muslim 2994', 232),
  ('Sneeze and Say Alhamdulillah', 'When you sneeze, say Alhamdulillah. The listener says Yarhamukallah.', 'health', 'Bukhari 6224', 233),
  ('Exercise and Stay Active', 'A strong believer is better and more beloved to Allah than a weak believer.', 'health', 'Muslim 2664', 234),
  ('Eat Slowly and Chew Well', 'The Prophet (PBUH) ate slowly and deliberately.', 'food', 'Various', 235),
  ('Don''t Eat While Standing', 'The Prophet (PBUH) forbade drinking while standing.', 'food', 'Muslim 2024', 236),
  ('Sit When Drinking Water', 'The Prophet (PBUH) preferred sitting while drinking.', 'food', 'Muslim 2024', 237),

  -- Days 238-267: Dhikr & Worship
  ('Say SubhanAllah 33 Times After Prayer', 'After prayer, say SubhanAllah 33 times, Alhamdulillah 33 times, Allahu Akbar 34 times.', 'daily', 'Muslim 597', 238),
  ('Say La ilaha illallah 100 Times', 'Whoever says La ilaha illallah 100 times has the reward of freeing 10 slaves.', 'daily', 'Bukhari 6403', 239),
  ('Say SubhanAllahi wa Bihamdihi 100 Times', 'Whoever says this 100 times, his sins will be forgiven even if like sea foam.', 'daily', 'Bukhari 6405', 240),
  ('Recite Surah Al-Ikhlas Three Times', 'Reciting it three times equals reading the entire Quran.', 'daily', 'Bukhari 5015', 241),
  ('Recite Al-Mu''awwidhatayn', 'Recite Surah Al-Falaq and An-Nas morning, evening, and before sleep.', 'daily', 'Abu Dawud 5056', 242),
  ('Say Hasbiyallahu la ilaha illa Huwa', 'Whoever says this seven times, Allah will suffice him.', 'daily', 'Abu Dawud 5081', 243),
  ('Make Istighfar 100 Times', 'I seek forgiveness from Allah 100 times a day.', 'daily', 'Muslim 2702', 244),
  ('Say Sayyid al-Istighfar', 'The master supplication for forgiveness: Allahumma anta Rabbi...', 'daily', 'Bukhari 6306', 245),
  ('Send Salawat on the Prophet 100 Times', 'Whoever sends blessings on me once, Allah sends 10 upon him.', 'daily', 'Muslim 408', 246),
  ('Read One Page of Quran', 'Read the Quran, for it will come as an intercessor on the Day of Judgment.', 'worship', 'Muslim 804', 247),
  ('Memorize a New Ayah', 'The best of you is the one who learns the Quran and teaches it.', 'worship', 'Bukhari 5027', 248),
  ('Reflect on a Verse', 'Do they not then reflect on the Quran?', 'worship', 'Quran 4:82', 249),
  ('Pray Two Rak''ah of Gratitude', 'When something good happens, pray two rak''ah of thanks to Allah.', 'salah', 'Abu Dawud 2774', 250),
  ('Make Dua at Suhoor Time', 'Allah descends to the lowest heaven in the last third of the night.', 'daily', 'Bukhari 1145', 251),
  ('Say Adhkar of the Market', 'Say La ilaha illallah when entering the marketplace.', 'daily', 'Tirmidhi 3428', 252),
  ('Say Bismillah When Entering Home', 'When entering say Bismillah and send peace upon the family.', 'daily', 'Abu Dawud 5096', 253),
  ('Say Dua When Leaving Home', 'Bismillah, tawakkaltu alallah, la hawla wa la quwwata illa billah.', 'daily', 'Abu Dawud 5095', 254),
  ('Make Dua When It Rains', 'Allahumma sayyiban nafi''an — O Allah, make it beneficial rain.', 'daily', 'Bukhari 1032', 255),
  ('Say Dua When Hearing Thunder', 'SubhanAllah-ladhi yusabbihu ar-ra''du bi hamdihi.', 'daily', 'Malik', 256),
  ('Make Dua While Traveling', 'The dua of a traveler is answered.', 'daily', 'Tirmidhi 3437', 257),
  ('Recite Quran After Fajr', 'The recitation at dawn is witnessed by the angels.', 'worship', 'Quran 17:78', 258),
  ('Attend Islamic Lectures', 'Gatherings of knowledge are gardens of Paradise.', 'worship', 'Tirmidhi 3510', 259),
  ('Fast Three Days Each Month', 'Fasting three days of each month is like fasting the entire year.', 'worship', 'Bukhari 1979', 260),
  ('Give Secret Charity', 'Seven will be shaded by Allah, including one who gives charity secretly.', 'worship', 'Bukhari 660', 261),
  ('Pray for the Deceased', 'When you pray janazah, sincerely supplicate for the deceased.', 'salah', 'Muslim 963', 262),
  ('Visit the Graveyard', 'Visit graves, for they remind you of the Hereafter.', 'worship', 'Muslim 976', 263),
  ('Fast the Day of Arafah', 'Fasting the Day of Arafah expiates the sins of the previous and coming year.', 'worship', 'Muslim 1162', 264),
  ('Fast Ashura', 'Fasting the day of Ashura expiates the sins of the previous year.', 'worship', 'Muslim 1162', 265),
  ('Observe I''tikaf', 'The Prophet (PBUH) used to observe I''tikaf in the last ten days of Ramadan.', 'worship', 'Bukhari 2025', 266),
  ('Pray Taraweeh', 'Whoever prays during Ramadan nights with faith, his past sins are forgiven.', 'salah', 'Bukhari 2009', 267),

  -- Days 268-297: Sleep, Travel & Daily Life
  ('Recite Three Quls Before Sleep', 'The Prophet (PBUH) would cup his hands, blow, and recite the three Quls.', 'sleep', 'Bukhari 5017', 268),
  ('Sleep Early After Isha', 'The Prophet (PBUH) disliked sleeping before Isha and talking after it.', 'sleep', 'Bukhari 568', 269),
  ('Nap in the Afternoon', 'Take the afternoon nap (qailulah) for it helps with tahajjud.', 'sleep', 'Ibn Majah', 270),
  ('Wake for Tahajjud', 'The best prayer after the obligatory prayers is the night prayer.', 'sleep', 'Muslim 1163', 271),
  ('Say the Dua for Insomnia', 'If unable to sleep, recite the remembrance of Allah.', 'sleep', 'Bukhari', 272),
  ('Don''t Sleep on Your Stomach', 'The Prophet (PBUH) said sleeping on the stomach is disliked by Allah.', 'sleep', 'Tirmidhi 2768', 273),
  ('Say Dua Upon Waking from Bad Dream', 'Spit lightly to the left three times and seek refuge in Allah.', 'sleep', 'Muslim 2261', 274),
  ('Say Dua Before Travel', 'SubhanAllah-ladhi sakh-khara lana hadha...', 'travel', 'Muslim 1342', 275),
  ('Pray Two Rak''ah Before Leaving', 'The Prophet (PBUH) would pray two rak''ah before traveling.', 'travel', 'Various', 276),
  ('Shorten Prayers When Traveling', 'Allah loves that His concessions be taken as He dislikes disobedience.', 'travel', 'Ahmad', 277),
  ('Combine Prayers When Traveling', 'The Prophet (PBUH) combined Dhuhr and Asr when traveling.', 'travel', 'Bukhari 1107', 278),
  ('Make Dua When Arriving', 'Say: A''udhu bi kalimatillahit-tammat when stopping at a place.', 'travel', 'Muslim 2708', 279),
  ('Return Home and Pray Two Rak''ah', 'When returning from travel, pray two rak''ah at the masjid.', 'travel', 'Bukhari 3088', 280),
  ('Bring Gifts from Travel', 'Give gifts, for it strengthens love.', 'travel', 'Bukhari-Adab', 281),
  ('Travel in a Group', 'A rider alone is a devil. Two riders are two devils. Three is a traveling group.', 'travel', 'Tirmidhi 1674', 282),
  ('Appoint a Leader When Traveling', 'When three travel, let them appoint one as leader.', 'travel', 'Abu Dawud 2608', 283),
  ('Say Bismillah When Starting Work', 'Begin every important matter with Bismillah.', 'daily', 'Abu Dawud 101', 284),
  ('Be Honest in Business', 'The truthful trustworthy merchant is with the prophets.', 'character', 'Tirmidhi 1209', 285),
  ('Don''t Cheat in Trade', 'Whoever cheats is not one of us.', 'character', 'Muslim 102', 286),
  ('Pay Workers Promptly', 'Give the worker his wages before his sweat dries.', 'people', 'Ibn Majah 2443', 287),
  ('Say Dua When Entering Masjid', 'Allahumma aftah li abwaba rahmatik.', 'daily', 'Muslim 713', 288),
  ('Say Dua When Leaving Masjid', 'Allahumma inni as-aluka min fadlik.', 'daily', 'Muslim 713', 289),
  ('Enter Masjid with Right Foot', 'Enter the masjid with your right foot.', 'worship', 'Bukhari-Adab', 290),
  ('Pray Tahiyyat al-Masjid', 'When entering the masjid, do not sit until you pray two rak''ah.', 'salah', 'Bukhari 1163', 291),
  ('Sit in the Front Rows', 'If people knew the reward of the first row, they would draw lots.', 'salah', 'Bukhari 615', 292),
  ('Fill Gaps in Prayer Rows', 'Whoever fills a gap in a row, Allah will raise him a degree.', 'salah', 'Ibn Majah', 293),
  ('Face the Qiblah When Making Dua', 'The Prophet (PBUH) would face the qiblah and raise his hands for dua.', 'daily', 'Bukhari 1031', 294),
  ('Raise Hands During Dua', 'Allah is shy to let His servant raise his hands and return them empty.', 'daily', 'Tirmidhi 3556', 295),
  ('Begin Dua with Praise', 'Start your dua by praising Allah and sending salawat on the Prophet.', 'daily', 'Tirmidhi 3476', 296),
  ('Use Allah''s Names in Dua', 'To Allah belong the most beautiful names, so call upon Him by them.', 'daily', 'Quran 7:180', 297),

  -- Days 298-335: More Character, Worship & Social
  ('Avoid Extravagance', 'Eat, drink, give charity, and wear clothes without extravagance or pride.', 'character', 'Ibn Majah', 298),
  ('Be Content with What You Have', 'Look at those below you, not above you, so you won''t belittle Allah''s blessings.', 'character', 'Muslim 2963', 299),
  ('Trust in Allah', 'If you relied on Allah as He should be relied on, He would provide like birds.', 'worship', 'Tirmidhi 2344', 300),
  ('Make Shura (Consultation)', 'The Prophet (PBUH) would consult his companions in important matters.', 'people', 'Quran 3:159', 301),
  ('Keep Secrets', 'Meetings are trusts. Don''t reveal what was said in private.', 'character', 'Abu Dawud 4869', 302),
  ('Don''t Spy on Others', 'Do not spy, do not look for faults, and do not be jealous.', 'character', 'Bukhari 6064', 303),
  ('Avoid Debt If Possible', 'The Prophet (PBUH) sought refuge from being overwhelmed by debt.', 'worship', 'Bukhari 2893', 304),
  ('Fulfill Your Oaths', 'Fulfill your agreements. Agreements will be questioned about.', 'character', 'Quran 17:34', 305),
  ('Be Patient With Children', 'The Prophet (PBUH) was the most patient with children.', 'people', 'Bukhari 5997', 306),
  ('Kiss and Hug Your Children', 'The Prophet (PBUH) kissed Al-Hasan and said: Whoever does not show mercy will not be shown mercy.', 'people', 'Bukhari 5997', 307),
  ('Teach Children to Pray at Seven', 'Command your children to pray at seven and discipline them at ten.', 'people', 'Abu Dawud 495', 308),
  ('Treat Daughters with Kindness', 'Whoever has three daughters and is patient with them, they will be a shield from the Fire.', 'people', 'Tirmidhi 1916', 309),
  ('Be Good to Your Spouse', 'The best of you is the one who is best to his family.', 'people', 'Tirmidhi 3895', 310),
  ('Help with Household Chores', 'The Prophet (PBUH) was at the service of his family.', 'people', 'Bukhari 676', 311),
  ('Say Dua for Your Parents', 'Rabbi irhamhuma kama rabbayani saghira.', 'daily', 'Quran 17:24', 312),
  ('Give Gifts to Each Other', 'Exchange gifts, for gifts remove grudges from the heart.', 'people', 'Tirmidhi 2130', 313),
  ('Say Jazakallah Khairan', 'Whoever has a favor done for him and says Jazakallah Khairan has thanked enough.', 'people', 'Tirmidhi 2035', 314),
  ('Cover Others'' Faults', 'Whoever covers the fault of a Muslim, Allah will cover his faults.', 'character', 'Muslim 2580', 315),
  ('Make Excuses for Others', 'Make seventy excuses for your brother.', 'character', 'Bayhaqi', 316),
  ('Avoid Arguing', 'I guarantee a house in Paradise for one who avoids arguing even if right.', 'character', 'Abu Dawud 4800', 317),
  ('Eat Suhoor', 'Eat suhoor, for in suhoor there is blessing.', 'food', 'Bukhari 1923', 318),
  ('Break Fast with Dates', 'The Prophet (PBUH) would break his fast with fresh dates.', 'food', 'Abu Dawud 2356', 319),
  ('Feed the Fasting Person', 'Whoever feeds a fasting person gets the same reward without diminishing theirs.', 'people', 'Tirmidhi 807', 320),
  ('Give Zakat al-Fitr', 'The Prophet (PBUH) obligated Zakat al-Fitr before Eid prayer.', 'worship', 'Bukhari 1503', 321),
  ('Say Takbir on Eid', 'Glorify Allah for guiding you and be grateful.', 'worship', 'Quran 2:185', 322),
  ('Pray Eid Prayer', 'The Prophet (PBUH) would go out for Eid prayer and take a different route back.', 'salah', 'Bukhari 986', 323),
  ('Wear Best Clothes on Eid', 'The Prophet (PBUH) had a special garment for Eid and Jumu''ah.', 'home', 'Bukhari', 324),
  ('Eat Before Eid al-Fitr Prayer', 'The Prophet (PBUH) would eat dates before going to Eid al-Fitr prayer.', 'food', 'Bukhari 953', 325),
  ('Say Dua When Looking in Mirror', 'Allahumma ahsanta khalqi fa ahsin khuluqi.', 'daily', 'Ahmad', 326),
  ('Respond to the Adhan', 'Say what the muadhin says, then send salawat and make dua.', 'daily', 'Muslim 384', 327),
  ('Say Inna lillahi When Afflicted', 'We belong to Allah and to Him we return.', 'daily', 'Quran 2:156', 328),
  ('Make Dua for Muslim Ummah', 'Pray for the entire Muslim community in your supplications.', 'daily', 'Muslim', 329),
  ('Read Surah Al-Mulk Before Sleep', 'The Prophet (PBUH) would not sleep until he recited Surah Al-Mulk.', 'worship', 'Tirmidhi 2892', 330),
  ('Pray Witr Before Sleeping', 'Make your last prayer of the night the witr prayer.', 'salah', 'Bukhari 998', 331),
  ('Tie Your Camel and Trust Allah', 'Tie your camel and then trust in Allah.', 'worship', 'Tirmidhi 2517', 332),
  ('Seek Refuge from Laziness', 'The Prophet (PBUH) sought refuge from inability and laziness.', 'daily', 'Bukhari 6369', 333),
  ('Renew Your Intention', 'Actions are by intentions. Renew your niyyah throughout the day.', 'worship', 'Bukhari 1', 334),
  ('End Your Day with Gratitude', 'If you are grateful, I will increase you.', 'worship', 'Quran 14:7', 335),

  -- Days 336-365: Review & Reinforce
  ('Review: Pray All Five on Time', 'The most beloved deed to Allah is prayer at its proper time.', 'salah', 'Bukhari 527', 336),
  ('Review: Perfect Your Wudu', 'No Muslim makes wudu and perfects it except that sins fall from his body.', 'home', 'Muslim 244', 337),
  ('Review: Say Bismillah Often', 'Every important matter not begun with Bismillah is cut off from blessing.', 'daily', 'Ibn Majah', 338),
  ('Review: Eat with Right Hand', 'Satan eats with his left hand. Eat with your right.', 'food', 'Muslim 2020', 339),
  ('Review: Sleep on Right Side', 'Lie down on your right side after making wudu and remembering Allah.', 'sleep', 'Bukhari 247', 340),
  ('Review: Smile and Be Kind', 'Do not belittle any good deed, even meeting your brother with a cheerful face.', 'character', 'Muslim 2626', 341),
  ('Review: Give Daily Charity', 'Every joint must give charity each day. Every tasbeehah is charity.', 'worship', 'Muslim 1007', 342),
  ('Review: Say Morning Adhkar', 'Protect yourself with the morning and evening adhkar.', 'daily', 'Abu Dawud 5068', 343),
  ('Review: Say Evening Adhkar', 'The evening remembrances are a shield until morning.', 'daily', 'Abu Dawud 5069', 344),
  ('Review: Read Quran Daily', 'The one skilled in Quran is with the noble angels.', 'worship', 'Bukhari 4937', 345),
  ('Review: Fast Voluntary Days', 'Whoever fasts a day for Allah, Allah distances his face from the Fire by 70 years.', 'worship', 'Bukhari 2840', 346),
  ('Review: Maintain Family Ties', 'Whoever wishes to have his provision expanded, let him maintain family ties.', 'people', 'Bukhari 5986', 347),
  ('Review: Control Anger', 'Don''t be angry. Don''t be angry. Don''t be angry.', 'character', 'Bukhari 6116', 348),
  ('Review: Make Much Istighfar', 'Whoever makes istighfar regularly, Allah provides a way out of every difficulty.', 'daily', 'Abu Dawud 1518', 349),
  ('Review: Pray Sunnah Prayers', 'Twelve rak''ah of sunnah: Allah builds a house in Paradise.', 'salah', 'Muslim 728', 350),
  ('Review: Be Good to Neighbors', 'He is not a believer whose neighbor is not safe from his harm.', 'people', 'Bukhari 6016', 351),
  ('Review: Honor Parents', 'The pleasure of Allah is in the pleasure of parents.', 'people', 'Tirmidhi 1899', 352),
  ('Review: Speak the Truth', 'Hold to truth, for truth leads to goodness.', 'character', 'Bukhari 6094', 353),
  ('Review: Make Dua Consistently', 'Dua is the essence of worship.', 'daily', 'Tirmidhi 3371', 354),
  ('Review: Visit the Sick', 'You are in the shade of Allah''s mercy when visiting the sick.', 'people', 'Muslim 2568', 355),
  ('Review: Lower the Gaze', 'Tell the believing men to lower their gaze and guard their chastity.', 'character', 'Quran 24:30', 356),
  ('Review: Use the Siwaak', 'The siwaak purifies the mouth and pleases the Lord.', 'home', 'An-Nasa''i 5', 357),
  ('Review: Sleep with Wudu', 'When you go to bed, perform ablution as for prayer.', 'sleep', 'Bukhari 247', 358),
  ('Review: Send Salawat Often', 'The closest to me on the Day of Judgment is the one who sent the most salawat.', 'daily', 'Tirmidhi 484', 359),
  ('Review: Seek Knowledge', 'Whoever follows a path seeking knowledge, Allah eases his path to Paradise.', 'worship', 'Muslim 2699', 360),
  ('Review: Remember Allah After Salah', 'SubhanAllah 33, Alhamdulillah 33, Allahu Akbar 34 after every prayer.', 'daily', 'Muslim 597', 361),
  ('Review: Be Generous Always', 'Protect yourselves from the Fire even with half a date.', 'worship', 'Bukhari 1417', 362),
  ('Review: Make Tawbah Daily', 'O people, repent to Allah, for I repent to Him 100 times a day.', 'worship', 'Muslim 2702', 363),
  ('Review: Trust in Allah''s Plan', 'If Allah loves a people, He tests them.', 'worship', 'Tirmidhi 2396', 364),
  ('Review: Strive for Jannah', 'Paradise is surrounded by hardships and the Fire by desires.', 'worship', 'Muslim 2822', 365);

-- Done seeding days 148-365
